language: python
python: 
  - "3.6"

services:
  - postgresql

env:
  -DJANGO=2.1 DB=postgresql

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test
  - coverage report -m

after_success:
  - coveralls