language: python
python: 
  - "3.6"

addons:
  postgresql: "9.6"

install: 
  - pip install pipenv
  - pipenv install
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c 'create database testdb;' -U postgres
  - python manage.py migrate

script:
  - coverage run --source='.' manage.py test
  - coverage report -m

after_success:
  - coveralls